### ISSUE TITLE
About consolidation of HttpRequest method.

### ISSUE THREAD

**Issue by rf0321** [lrf141/Twitter4S#2]
Hello, I have one suggestion. ```HttpRequest.scala``` in ```net``` package has two method that get and post.But written content same mostly. In there, I suggest that method name send in method param. In addition,If you want to POST request only then,  setRequestMethod("POST").
image
```java
if(mehod.equal("POST")){
    urlconnection.setRequestMethod("POST");
}
```

**Comment by lrf141** [comment]
Thank you for sending the issue.
I understood your Suggestion.
But I don't understood any asset that I can get with this.
I think that the nature of GET and POST is different in HTTP.
Is it a problem to integrate things with different properties? (show other HTTP method)
Please tell me the clear asset by this. (Other than shortening the code)

P.S.
The sample you presented is wrong.
At first "mehod" -> "method", "equal" -> "equals". It's a simple misspelling.
Next, It isn't a big mistake. 
You can also use setRequestMethod when using the GET method.
Therefore, it can be modified as follows

```java
//if( method.equals("POST") )
    urlconnection.setRequestMethod(method); //method expected GET or POST
```

**Comment by rf0321** [comment]
Thank you for replying me. I understood why you divide method. ;)
